name: Danger

on:
  pull_request:
    branches:
      - master

jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: yarn add danger --dev
      - name: Checkout the Git repository
        uses: actions/checkout@v1
      - name: Check
        run: yarn danger ci --failOnErrors
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
