name: Danger

on:
  pull_request:
    branches:
      - master

jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v1
      - name: Check
        run: |
          yarn global add danger
          danger ci --failOnErrors
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
