name: Danger

on:
  pull_request:
    branches:
      - master

jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v1
      - name: Check
        run: |
          yarn init --yes  
          yarn add danger --dev
          yarn danger ci --failOnErrors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
